root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o repo-analyzer cmd/cli/*.go"
bin = "repo-analyzer"
full_bin = "./repo-analyzer"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
include_dir = ["cmd", "pkg"]
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 